AWSTemplateFormatVersion: "2010-09-69"
Description: "Deploy a Network Gateway"
Parameters:

  PublicSubnetId:
    Description: The id of the public subnet deployed in Subnet Stack
    Type: String

Resources:
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnetId

  NatGateway1EIP:
      Type: AWS::EC2::EIP      
      Properties:
        Domain: vpc

Outputs:
  NatGateway:
    Value: !Ref NatGateway1 
    Description: A reference to the Nat Gateway
