AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy a subnet stack' 

Parameters:
  PublicSubnetCidr: 
    Description: The CIDR block for the public subnet located in Availability Zone 1.
    Type: String

  PrivateSubnetCidr:
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Type: String
  
  VpcId: 
    Description: A reference to the VPC creates in VpcStack,
    Type: String

Resources:
PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:     
      AvailabilityZone: !Select [ 0, !GetAZs '']
      CidrBlock: !Ref PublicSubnetCidr    
      MapPublicIpOnLaunch: true      
      Tags: 
        - Key: Name
          Value: public-subnet-substack
      VpcId: !Ref VpcId

PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:     
      AvailabilityZone: !Select [ 1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnetCidr    
      MapPublicIpOnLaunch: true      
      Tags: 
        - Key: Name
          Value: private-subnet-substack
      VpcId: !Ref VpcId

Outputs:
  PublicSubnetId:
    Value: !Ref PublicSubnet 
    Description: The id of the public subnet

  PrivateSubnetId:
    Value: !Ref PrivateSubnet 
    Description: The id of the public subnet
